sudo: required

language: generic

services:
  - docker

before_install: 
  - echo "start creating an image with dockerfile"
  - docker build -t choicco89/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true choicco89/docker-react npm run test -- --coverage

after_success:
  - echo "Test success"